### ISSUE TITLE
Bump to reveal.js 3.8.0

### ISSUE THREAD

**Issue by GaryJones** [aaroncampbell/presenter#2]
https://github.com/hakimel/reveal.js/releases/tag/3.6.0

**Comment by timnolte** [comment]
Reveal.js is now at version 3.8.0, if I have some time I might just submit a PR if it will get accepted.

**Comment by aaroncampbell** [comment]
Hey @timnolte, I've been pretty busy as of late so my responses may be a bit delayed here but I would LOVE to see a pull request to update reveal.js and would definitely be open to accepting it :)
